api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import BookViewSet


router = DefaultRouter()
router.register(r'books', BookViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

books/urls.py
from django.urls import path

from books.views import (
    BookFilterListView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
    LanguageListView,
    LanguageCreateView,
    LanguageUpdateView,
    LanguageDeleteView,
    api_import
)


urlpatterns = [
    path(
        'book/list/',
        BookFilterListView.as_view(),
        name='book-list'),
    path(
        'book/create/',
        BookCreateView.as_view(),
        name='book-create'),
    path(
        'book/<int:pk>/edit/',
        BookUpdateView.as_view(),
        name='book-edit'),
    path(
        'book/<int:pk>/delete/',
        BookDeleteView.as_view(),
        name='book-delete'),
    path(
        'author/list/',
        AuthorListView.as_view(),
        name='author-list'),
    path(
        'author/create/',
        AuthorCreateView.as_view(),
        name='author-create'),
    path(
        'author/<int:pk>/edit/',
        AuthorUpdateView.as_view(),
        name='author-edit'),
    path(
        'author/<int:pk>/delete/',
        AuthorDeleteView.as_view(),
        name='author-delete'),
    path(
        'language/list/',
        LanguageListView.as_view(),
        name='language-list'),
    path(
        'language/create/',
        LanguageCreateView.as_view(),
        name='language-create'),
    path(
        'language/<int:pk>/edit/',
        LanguageUpdateView.as_view(),
        name='language-edit'),
    path(
        'language/<int:pk>/delete/',
        LanguageDeleteView.as_view(),
        name='language-delete'),
    path(
        'import/',
        api_import,
        name='api-import')
]

project/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='books:book-list'),
         name='dashboard'),
    path('collection/', include(('books.urls', 'books'), namespace='books')),
    path('api/', include('api.urls'))
]

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Book app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>
  <body>
    <a href="{% url 'books:book-create' %}">Add book</a>
    <a href="{% url 'books:author-create' %}">Add author</a>
    <a href="{% url 'books:language-create' %}">Add language</a>
    <a href="{% url 'books:api-import' %}">Import books</a>
    {% block content %}{% endblock %}
  </body>
</html>