api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import BookViewSet


router = DefaultRouter()
router.register(r'books', BookViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

books/urls.py
from django.urls import path

from books.views import (
    BookFilterListView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
    LanguageListView,
    LanguageCreateView,
    LanguageUpdateView,
    LanguageDeleteView,
    api_import
)


urlpatterns = [
    path(
        'book/list/',
        BookFilterListView.as_view(),
        name='book-list'),
    path(
        'book/create/',
        BookCreateView.as_view(),
        name='book-create'),
    path(
        'book/<int:pk>/edit/',
        BookUpdateView.as_view(),
        name='book-edit'),
    path(
        'book/<int:pk>/delete/',
        BookDeleteView.as_view(),
        name='book-delete'),
    path(
        'author/list/',
        AuthorListView.as_view(),
        name='author-list'),
    path(
        'author/create/',
        AuthorCreateView.as_view(),
        name='author-create'),
    path(
        'author/<int:pk>/edit/',
        AuthorUpdateView.as_view(),
        name='author-edit'),
    path(
        'author/<int:pk>/delete/',
        AuthorDeleteView.as_view(),
        name='author-delete'),
    path(
        'language/list/',
        LanguageListView.as_view(),
        name='language-list'),
    path(
        'language/create/',
        LanguageCreateView.as_view(),
        name='language-create'),
    path(
        'language/<int:pk>/edit/',
        LanguageUpdateView.as_view(),
        name='language-edit'),
    path(
        'language/<int:pk>/delete/',
        LanguageDeleteView.as_view(),
        name='language-delete'),
    path(
        'import/',
        api_import,
        name='api-import')
]

project/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='books:book-list'),
         name='dashboard'),
    path('collection/', include(('books.urls', 'books'), namespace='books')),
    path('api/', include('api.urls'))
]

books/models.py
from typing import Optional, List, Any
from django.db import models
from django.core.validators import MaxValueValidator
from django.db.models.constraints import UniqueConstraint
from django.core.exceptions import ValidationError


PUBLISHED_YEAR_MAX = 2099
PAGE_COUTN_MAX = 15000


def validate_isbn(isbn: int) -> Optional[ValidationError]:
    """ Method for validation ISBN number. """
    ISBN_10_MIN = 10**9
    ISBN_10_MAX = 10**10
    ISBN_13_MIN = 10**12
    ISBN_13_MAX = 10**13
    if (isbn < ISBN_10_MIN or isbn >= ISBN_10_MAX) and (
            isbn < ISBN_13_MIN or isbn >= ISBN_13_MAX):
        raise ValidationError(('ISBN number should have 10 or 13 digits.'),
                              params={'isbn': isbn},
                              )


class AuthorManager(models.Manager):
    """ Author custom manager class. """

    def get_or_create_many(self, authors: List[str]) -> List[Any]:
        """ Method which gets or creates (if doesn't exists) author objects
        from passed authors string list, and returns a list with objects. """
        FIRST_NAME = 0
        SECOND_NAME = 1
        LAST_NAME = -1
        FIRST_LETTER = 0
        result_list = []
        for author in authors:
            author = author.split()
            count = self.get_queryset().filter(
                last_name=author[LAST_NAME]).count()
            if not count:
                obj = self.create(first_name=author[FIRST_NAME], second_name=' '.join(
                    author[SECOND_NAME:LAST_NAME]), last_name=author[LAST_NAME])
                result_list.append(obj)
            else:
                count = self.get_queryset().filter(
                    first_name__startswith=author[FIRST_NAME][FIRST_LETTER],
                    last_name=author[LAST_NAME]).count()
                if not count:
                    obj = self.create(first_name=author[FIRST_NAME], second_name=' '.join(
                        author[SECOND_NAME:LAST_NAME]), last_name=author[LAST_NAME])
                    result_list.append(obj)
                else:
                    obj = self.get(
                        first_name__startswith=author[FIRST_NAME][FIRST_LETTER],
                        last_name=author[LAST_NAME])
                    result_list.append(obj)
        return result_list


class Author(models.Model):
    """ Authors model class. """
    objects = AuthorManager()
    first_name = models.CharField(max_length=50)
    second_name = models.CharField(max_length=100, default='')
    last_name = models.CharField(max_length=50)

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=[
                    'first_name',
                    'last_name'],
                name='unique_author')]

    def __str__(self):
        return f"{self.first_name} {self.second_name} {self.last_name}"

    def __repr__(self):
        return f"<Author(first_name='{self.first_name}', second_name='{self.second_name}', \
            last_name='{self.last_name}')>"


class Language(models.Model):
    """ Languages model class. """
    language = models.CharField(max_length=50)
    shortcut = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return f"{self.language} ({self.shortcut})"

    def __repr__(self):
        return f"<Language(language='{self.language}', shortcut='{self.shortcut}')>"


class Book(models.Model):
    """ Books model class. """
    title = models.CharField(max_length=150)
    publication_year = models.PositiveIntegerField(
        validators=[MaxValueValidator(PUBLISHED_YEAR_MAX)])
    isbn = models.PositiveIntegerField(
        null=True, blank=True, validators=[validate_isbn])
    page_count = models.PositiveIntegerField(
        null=True, blank=True, validators=[
            MaxValueValidator(PAGE_COUTN_MAX)])
    cover_link = models.URLField(max_length=200, null=True, blank=True)

    language = models.ForeignKey(
        Language,
        related_name='books',
        on_delete=models.PROTECT)
    authors = models.ManyToManyField(
        Author, related_name='books', through='BookAuthor')

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=[
                    'title',
                    'publication_year',
                    'language'],
                name='unique_book')]

    def __str__(self):
        return f"{self.title} {self.publication_year}, isbn={self.isbn}, pages: {self.page_count}"

    def __repr__(self):
        return f"<Book(title='{self.title}', publication_year='{self.publication_year}', \
            isbn={self.isbn}, page_count='{self.page_count}', cover_link='{self.cover_link}')>"


class BookAuthor(models.Model):
    """ Model class for storing Author and Book relations. """
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

books/forms.py
from typing import Optional
from urllib.parse import urlparse
from django import forms
from django.core.exceptions import ValidationError


def validate_googleapis_hostname(url: str) -> Optional[ValidationError]:
    """ Method for validation is hostname belongs to Google APIs. """
    url = urlparse(url)
    if url.hostname not in ['googleapis.com', 'www.googleapis.com']:
        raise ValidationError('Only Google APIs URL allowed')


class ApiImportForm(forms.Form):
    """ Form for passing External API URL. """
    url = forms.URLField(
        label='External API URL',
        required=True,
        validators=[validate_googleapis_hostname])

books/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django_filters.views import FilterView
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from books.models import Author, Book, Language
from books.filters import BookFilter
from books.forms import ApiImportForm
from books.external_api import ExternalApi


class BookFilterListView(FilterView):
    """ Book filter list view class. """
    filterset_class = BookFilter


class BookCreateView(CreateView):
    """ Book create view class. """
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books:book-list')


class BookUpdateView(UpdateView):
    """ Book update view class. """
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books:book-list')


class BookDeleteView(DeleteView):
    """ Book delete view class. """
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books:book-list')


class AuthorListView(ListView):
    """ Author list view class. """
    model = Author


class AuthorCreateView(CreateView):
    """ Author create view class. """
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('books:author-list')


class AuthorUpdateView(UpdateView):
    """ Author update view class. """
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('books:author-list')


class AuthorDeleteView(DeleteView):
    """ Author delete view class. """
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('books:author-list')


class LanguageListView(ListView):
    """ Language list view class. """
    model = Language


class LanguageCreateView(CreateView):
    """ Language create view class. """
    model = Language
    fields = '__all__'
    success_url = reverse_lazy('books:language-list')


class LanguageUpdateView(UpdateView):
    """ Language update view class. """
    model = Language
    fields = '__all__'
    success_url = reverse_lazy('books:language-list')


class LanguageDeleteView(DeleteView):
    """ Language delete view class. """
    model = Language
    fields = '__all__'
    success_url = reverse_lazy('books:language-list')


def api_import(request):
    """ View for import data from external API. """
    if request.method == 'POST':
        form = ApiImportForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            external_api = ExternalApi(url)
            total = external_api.import_books()
            return redirect('books:book-list')
    else:
        form = ApiImportForm()
    return render(request, 'books/api_import.html', {'form': form})

books/templates/books/api_import.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Import</button>
</form>

{% endblock %}

books/templates/books/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Delete</button>
</form>

{% endblock %}

books/templates/books/author_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}

books/templates/books/author_list.html
{% extends "base.html" %}

{% block content %}

<table border="1">
    <thead>
      <tr>
        <th>First name</th>
        <th>Other names</th>
        <th>Last name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.first_name }}</td>
            <td>{{ obj.second_name|default:"-" }}</td>
            <td>{{ obj.last_name }}</td>
            <td>
            <a href="{% url 'books:author-edit' obj.id %}">Edit</a>
            <a href="{% url 'books:author-delete' obj.id %}">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No authors</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

books/templates/books/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Delete</button>
</form>

{% endblock %}

books/templates/books/book_filter.html
{% extends "base.html" %}

{% block content %}

<form method="get">
    {% csrf_token %}
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
</form>
<br>

<table border="1">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Publication year</th>
        <th>ISBN</th>
        <th>Pages</th>
        <th>Cover</th>
        <th>Language</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in filter.qs %}
        <tr>
            <td>"{{ obj.title|default:"-" }}"</td>
            <td>
            {% for author in obj.authors.all %}
                {{ author|default:"-" }}<br>
            {% endfor %}
            </td>
            <td>{{ obj.publication_year }}</td>
            <td>{{ obj.isbn|default:"-" }}</td>
            <td>{{ obj.page_count|default:"-" }}</td>
            <td>{{ obj.cover_link|default:"-" }}</td>
            <td>{{ obj.language }}</td>
            <td>
            <a href="{% url 'books:book-edit' obj.id %}">Edit</a>
            <a href="{% url 'books:book-delete' obj.id %}">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="8">No books</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

books/templates/books/book_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}

books/templates/books/language_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Delete</button>
</form>

{% endblock %}

books/templates/books/language_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

{% endblock %}

books/templates/books/language_list.html
{% extends "base.html" %}

{% block content %}

<table border="1">
    <thead>
      <tr>
        <th>Language</th>
        <th>Shortcut</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.language|default:"-" }}</td>
            <td>({{ obj.shortcut }})</td>
            <td>
            <a href="{% url 'books:language-edit' obj.id %}">Edit</a>
            <a href="{% url 'books:language-delete' obj.id %}">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No languages</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}